name = "Engimo"
license = "MIT"
licenselink = "https://github.com/achary/engimo/blob/master/LICENSE"
description = "Minimalist theme for Engineers"
homepage = "https://engimo.netlify.com"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive",
  "engineering"
]
features = [
  "accessibility",
  "algolia",
  "analytics",
  "comments",
  "cover-image",
  "disqus",
  "entry-navigation",
  "favicon",
  "fuse.js",
  "lunr.js",
  "multilingual",
  "multi-author",
  "opengraph",
  "pagination",
  "search",
  "shortcodes",
  "sidebar",
  "single-column",
  "social-menu",
  "staticman",
  "syntax-highlighting",
  "table-of-contents",
  "utterances",
  "widgets",
  "graphviz",
  "wavedrom",
  "deprecated-pages",
  "mathjax"
]
min_version = 0.45

[author]
  name = "Adam Charytoniuk"
  homepage = "https://github.com/achary/engimo"

[original]
  name = "Munif Tanjim"
  homepage = "https://muniftanjim.com"
  repo = "https://github.com/MunifTanjim/minimo"