baseURL = "http://www.example.com"
title = "Minimo"
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""
Paginate = 5

[params]
  description = "Minimalist theme for Hugo"
  dateFormat = "2006, Jan 2"
  copyrightOwner = "MunifTanjim"
  copyrightStartYear = "2017"
  favicon = "favicon.ico"
  hideEntryNavigation = false
  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

[params.opengraph]
  [params.opengraph.facebook]
    admins = ""
    appid = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  facebook = ""

[author]
  name = "Minimo"

[author.social]
  codepen = "MunifTanjim"
  facebook = "MunifTanjim"
  github = "MunifTanjim/minimo"
  instagram = "instagram"
  twitter = "MunifTanjim"

[permalinks]
  page = "/:slug/"

[[menu.main]]
  name = "Repo"
  weight = -70
  identifier = "repository"
  url = "https://github.com/MunifTanjim/minimo"

# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
